version: '3'

services:
  nginx_web_1:
    image: nginx:latest
    container_name: nginx_web_proyecto1
    restart: always
    volumes:
      - ./nginx/web1:/usr/share/nginx/html
    ports:
      - 8081:80
    networks:
      - web_network

  nginx_web_2:
    image: nginx:latest
    container_name: nginx_web_proyecto2
    restart: always
    volumes:
      - ./nginx/web2:/usr/share/nginx/html
    ports:
      - 8082:80
    networks:
      - web_network

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    restart: always
    ports:
      - 80:80
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - web_network

networks:
  web_network:
