version: '3'
 
services:
  nginx_web_1:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8081:80
    networks:
      - frontend_network

  nginx_web_2:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8082:80
    networks:
      - frontend_network

  haproxy:
    image: haproxy:latest
    ports:
      - 80:80
    networks:
      - frontend_network
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

networks:
  frontend_network:
