version: "3"
services:
  monit:
    image: mmonit/mmonit:3.7.4
    container_name: mmonit
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - MMONIT_LICENSE_OWNER="Fred"
      - MMONIT_LICENSE_KEY="<M/Monit license key>"
    volumes:
      - /root/Desktop/Proyecto/Monitorizar:/config
    ports:
      - 8080:8080
    restart: unless-stopped
